[package]
name = "sund"
version = "0.1.0"
edition = "2021"
description = "Sund is a suspendable json parser core that unifies buffered and streaming JSON decoding."
authors = ["penglei"]
license = "MIT"
repository = "https://github.com/velox-io/sund-rs"
homepage = "https://github.com/velox-io/sund-rs"
documentation = "https://docs.rs/sund"
keywords = ["json", "parser", "streaming", "async"]
categories = ["encoding", "parser-implementations"]
readme = "README.md"

[dependencies]
