[workspace]
resolver = "2"
members = [
    "crates/sund-json",
    "crates/sund-derive",
    "sund",
    "benches/sund-bench",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["penglei"]
license = "MIT"
repository = "https://github.com/penglei/sund-rs"
homepage = "https://github.com/penglei/sund-rs"
keywords = ["json", "parser", "streaming", "simd"]
categories = ["encoding", "parser-implementations"]

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
